[package]
name = "Bloctonum"
version = "0.1.0"
authors = ["KevDev0247 <donkevin1980s@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
